# Generated by Django 5.1.3 on 2024-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="targets",
        ),
        migrations.AddField(
            model_name="mission",
            name="targets",
            field=models.ManyToManyField(
                blank=True, related_name="missions", to="missions.target"
            ),
        ),
    ]
