# Generated by Django 5.1.3 on 2024-11-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0002_remove_mission_targets_mission_targets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="name",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="updated_at",
        ),
    ]
