# Generated by Django 5.1.3 on 2024-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0003_remove_mission_created_at_remove_mission_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mission",
            old_name="cats",
            new_name="cat",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="target",
            name="status",
        ),
        migrations.AddField(
            model_name="mission",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="target",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
