# Generated by Django 5.1.3 on 2024-11-19 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0004_rename_cats_mission_cat_remove_mission_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="targets",
        ),
        migrations.AddField(
            model_name="mission",
            name="targets",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions",
                to="missions.target",
            ),
        ),
    ]
