# Generated by Django 5.1.3 on 2024-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("years_of_experience", models.IntegerField()),
                ("breed", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
